version: '3.8'

services:
  db:
    container_name: '${NAME}_mysql'
    image: mariadb:latest
    restart: always
    volumes:
      - ${VOLUME_PATH}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    ports:
      - 3306:3306
